import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';

export type ExportFormat = 'pdf' | 'excel' | 'csv';

interface ExportData {
  title: string;
  data: any[];
  columns: { key: string; label: string; width?: number }[];
  metadata?: {
    generatedAt?: Date;
    generatedBy?: string;
    filters?: Record<string, any>;
    summary?: Record<string, any>;
  };
}

interface ExportOptions {
  filename?: string;
  includeTimestamp?: boolean;
  includeMetadata?: boolean;
  orientation?: 'portrait' | 'landscape';
  pageSize?: 'a4' | 'letter';
}

class ExportUtility {
  private formatFilename(title: string, format: ExportFormat, options: ExportOptions = {}): string {
    const timestamp = options.includeTimestamp !== false 
      ? `_${new Date().toISOString().split('T')[0]}` 
      : '';
    const baseFilename = options.filename || title.toLowerCase().replace(/\s+/g, '_');
    return `${baseFilename}${timestamp}.${format}`;
  }

  private sanitizeForCSV(value: any): string {
    if (value === null || value === undefined) return '';
    const str = String(value);
    if (str.includes(',') || str.includes('"') || str.includes('\n')) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  }

  async exportToCSV(exportData: ExportData, options: ExportOptions = {}): Promise<void> {
    const { title, data, columns, metadata } = exportData;
    
    let csvContent = '';
    
    // Add metadata if requested
    if (options.includeMetadata && metadata) {
      csvContent += `# ${title}\n`;
      if (metadata.generatedAt) {
        csvContent += `# Generated: ${metadata.generatedAt.toISOString()}\n`;
      }
      if (metadata.generatedBy) {
        csvContent += `# Generated by: ${metadata.generatedBy}\n`;
      }
      if (metadata.filters && Object.keys(metadata.filters).length > 0) {
        csvContent += `# Filters: ${JSON.stringify(metadata.filters)}\n`;
      }
      csvContent += '\n';
    }
    
    // Add headers
    csvContent += columns.map(col => this.sanitizeForCSV(col.label)).join(',') + '\n';
    
    // Add data rows
    data.forEach(row => {
      const rowData = columns.map(col => this.sanitizeForCSV(row[col.key]));
      csvContent += rowData.join(',') + '\n';
    });
    
    // Create and download file
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const filename = this.formatFilename(title, 'csv', options);
    saveAs(blob, filename);
  }

  async exportToExcel(exportData: ExportData, options: ExportOptions = {}): Promise<void> {
    const { title, data, columns, metadata } = exportData;
    
    // Create workbook
    const workbook = XLSX.utils.book_new();
    
    // Prepare data for worksheet
    const worksheetData: any[][] = [];
    
    // Add metadata if requested
    if (options.includeMetadata && metadata) {
      worksheetData.push([title]);
      worksheetData.push([]);
      
      if (metadata.generatedAt) {
        worksheetData.push(['Generated:', metadata.generatedAt.toISOString()]);
      }
      if (metadata.generatedBy) {
        worksheetData.push(['Generated by:', metadata.generatedBy]);
      }
      if (metadata.summary) {
        worksheetData.push(['Summary:']);
        Object.entries(metadata.summary).forEach(([key, value]) => {
          worksheetData.push([key, value]);
        });
      }
      worksheetData.push([]);
    }
    
    // Add headers
    worksheetData.push(columns.map(col => col.label));
    
    // Add data rows
    data.forEach(row => {
      worksheetData.push(columns.map(col => row[col.key]));
    });
    
    // Create worksheet
    const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);
    
    // Set column widths
    const colWidths = columns.map(col => ({ 
      wch: col.width || Math.max(col.label.length, 15) 
    }));
    worksheet['!cols'] = colWidths;
    
    // Add worksheet to workbook
    XLSX.utils.book_append_sheet(workbook, worksheet, title.substring(0, 31));
    
    // Generate and download file
    const filename = this.formatFilename(title, 'excel', options);
    XLSX.writeFile(workbook, filename.replace('.excel', '.xlsx'));
  }

  async exportToPDF(exportData: ExportData, options: ExportOptions = {}): Promise<void> {
    const { title, data, columns, metadata } = exportData;
    
    // Create PDF
    const orientation = options.orientation || 'portrait';
    const format = options.pageSize || 'a4';
    const pdf = new jsPDF({
      orientation,
      unit: 'mm',
      format,
    });
    
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 20;
    let yPosition = margin;
    
    // Title
    pdf.setFontSize(16);
    pdf.setFont(undefined, 'bold');
    pdf.text(title, margin, yPosition);
    yPosition += 10;
    
    // Metadata
    if (options.includeMetadata && metadata) {
      pdf.setFontSize(10);
      pdf.setFont(undefined, 'normal');
      
      if (metadata.generatedAt) {
        pdf.text(`Generated: ${metadata.generatedAt.toLocaleString()}`, margin, yPosition);
        yPosition += 5;
      }
      
      if (metadata.generatedBy) {
        pdf.text(`Generated by: ${metadata.generatedBy}`, margin, yPosition);
        yPosition += 5;
      }
      
      if (metadata.filters && Object.keys(metadata.filters).length > 0) {
        pdf.text('Filters:', margin, yPosition);
        yPosition += 5;
        Object.entries(metadata.filters).forEach(([key, value]) => {
          if (value) {
            pdf.text(`  ${key}: ${value}`, margin + 5, yPosition);
            yPosition += 4;
          }
        });
      }
      
      yPosition += 10;
    }
    
    // Table headers
    const columnWidth = (pageWidth - 2 * margin) / columns.length;
    
    pdf.setFontSize(10);
    pdf.setFont(undefined, 'bold');
    
    columns.forEach((col, index) => {
      const x = margin + index * columnWidth;
      pdf.text(col.label, x, yPosition);
    });
    
    yPosition += 7;
    
    // Draw header line
    pdf.line(margin, yPosition - 2, pageWidth - margin, yPosition - 2);
    
    // Table data
    pdf.setFont(undefined, 'normal');
    
    data.forEach((row, rowIndex) => {
      // Check if we need a new page
      if (yPosition > pageHeight - margin - 10) {
        pdf.addPage();
        yPosition = margin;
        
        // Redraw headers on new page
        pdf.setFont(undefined, 'bold');
        columns.forEach((col, index) => {
          const x = margin + index * columnWidth;
          pdf.text(col.label, x, yPosition);
        });
        yPosition += 7;
        pdf.line(margin, yPosition - 2, pageWidth - margin, yPosition - 2);
        pdf.setFont(undefined, 'normal');
      }
      
      columns.forEach((col, colIndex) => {
        const x = margin + colIndex * columnWidth;
        const cellValue = String(row[col.key] || '');
        
        // Truncate long text to fit column
        const maxWidth = columnWidth - 2;
        const truncatedText = pdf.getTextWidth(cellValue) > maxWidth
          ? cellValue.substring(0, Math.floor(cellValue.length * maxWidth / pdf.getTextWidth(cellValue))) + '...'
          : cellValue;
        
        pdf.text(truncatedText, x, yPosition);
      });
      
      yPosition += 6;
    });
    
    // Add page numbers
    const pageCount = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.text(
        `Page ${i} of ${pageCount}`,
        pageWidth - margin - 20,
        pageHeight - 10
      );
    }
    
    // Save file
    const filename = this.formatFilename(title, 'pdf', options);
    pdf.save(filename);
  }

  async exportFromTableElement(
    tableElement: HTMLElement,
    title: string,
    format: ExportFormat,
    options: ExportOptions = {}
  ): Promise<void> {
    if (format === 'pdf') {
      const canvas = await html2canvas(tableElement, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#ffffff',
      });
      
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: options.orientation || 'landscape',
        unit: 'mm',
        format: options.pageSize || 'a4',
      });
      
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 10;
      
      // Add title
      pdf.setFontSize(16);
      pdf.text(title, margin, margin);
      
      // Calculate image dimensions
      const imgWidth = pageWidth - 2 * margin;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      // Add image
      if (imgHeight <= pageHeight - 2 * margin - 10) {
        pdf.addImage(imgData, 'PNG', margin, margin + 10, imgWidth, imgHeight);
      } else {
        // Split across multiple pages if needed
        let remainingHeight = imgHeight;
        let yOffset = 0;
        let pageNum = 1;
        
        while (remainingHeight > 0) {
          if (pageNum > 1) {
            pdf.addPage();
          }
          
          const currentPageHeight = Math.min(remainingHeight, pageHeight - 2 * margin);
          pdf.addImage(
            imgData,
            'PNG',
            margin,
            pageNum === 1 ? margin + 10 : margin,
            imgWidth,
            imgHeight,
            '',
            'NONE',
            0,
            -yOffset
          );
          
          remainingHeight -= currentPageHeight;
          yOffset += currentPageHeight;
          pageNum++;
        }
      }
      
      const filename = this.formatFilename(title, 'pdf', options);
      pdf.save(filename);
    } else {
      // For CSV and Excel, extract data from table
      const rows = Array.from(tableElement.querySelectorAll('tr'));
      if (rows.length === 0) return;
      
      const headerCells = Array.from(rows[0].querySelectorAll('th, td'));
      const columns = headerCells.map((cell, index) => ({
        key: index.toString(),
        label: cell.textContent?.trim() || `Column ${index + 1}`,
      }));
      
      const data = rows.slice(1).map(row => {
        const cells = Array.from(row.querySelectorAll('td, th'));
        const rowData: Record<string, string> = {};
        cells.forEach((cell, index) => {
          rowData[index.toString()] = cell.textContent?.trim() || '';
        });
        return rowData;
      });
      
      const exportData: ExportData = {
        title,
        data,
        columns,
        metadata: {
          generatedAt: new Date(),
          ...options.includeMetadata && {
            generatedBy: 'Export System',
          },
        },
      };
      
      if (format === 'csv') {
        await this.exportToCSV(exportData, options);
      } else if (format === 'excel') {
        await this.exportToExcel(exportData, options);
      }
    }
  }

  async exportReport(
    exportData: ExportData,
    format: ExportFormat,
    options: ExportOptions = {}
  ): Promise<void> {
    try {
      switch (format) {
        case 'csv':
          await this.exportToCSV(exportData, options);
          break;
        case 'excel':
          await this.exportToExcel(exportData, options);
          break;
        case 'pdf':
          await this.exportToPDF(exportData, options);
          break;
        default:
          throw new Error(`Unsupported export format: ${format}`);
      }
    } catch (error) {
      console.error('Export failed:', error);
      throw new Error(`Failed to export as ${format}: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }
}

// Create singleton instance
export const exportUtility = new ExportUtility();

// Convenience functions
export const exportToCSV = (data: ExportData, options?: ExportOptions) => 
  exportUtility.exportToCSV(data, options);

export const exportToExcel = (data: ExportData, options?: ExportOptions) => 
  exportUtility.exportToExcel(data, options);

export const exportToPDF = (data: ExportData, options?: ExportOptions) => 
  exportUtility.exportToPDF(data, options);

export const exportFromTable = (
  tableElement: HTMLElement,
  title: string,
  format: ExportFormat,
  options?: ExportOptions
) => exportUtility.exportFromTableElement(tableElement, title, format, options);

export const exportReport = (
  data: ExportData,
  format: ExportFormat,
  options?: ExportOptions
) => exportUtility.exportReport(data, format, options);