name: Test Secrets Configuration

on:
  workflow_dispatch:
  push:
    branches:
      - test/deployment-workflow

jobs:
  test-secrets:
    name: Verify Secrets are Configured
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Required Secrets
        run: |
          echo "Testing if secrets are configured..."
          echo "=================================="
          
          # Test each secret (will show length, not actual value)
          if [ -n "${{ secrets.EC2_SSH_KEY }}" ]; then
            echo "✅ EC2_SSH_KEY is set (length: ${#SECRET})"
          else
            echo "❌ EC2_SSH_KEY is NOT set"
          fi
          
          if [ -n "${{ secrets.EC2_HOST_DEV }}" ]; then
            echo "✅ EC2_HOST_DEV is set"
            echo "   Value: ${{ secrets.EC2_HOST_DEV }}"
          else
            echo "❌ EC2_HOST_DEV is NOT set"
          fi
          
          if [ -n "${{ secrets.PERSONAL_ACCESS_TOKEN }}" ]; then
            echo "✅ PERSONAL_ACCESS_TOKEN is set"
          else
            echo "❌ PERSONAL_ACCESS_TOKEN is NOT set"
          fi
          
          if [ -n "${{ secrets.NEXT_PUBLIC_API_URL }}" ]; then
            echo "✅ NEXT_PUBLIC_API_URL is set"
            echo "   Value: ${{ secrets.NEXT_PUBLIC_API_URL }}"
          else
            echo "❌ NEXT_PUBLIC_API_URL is NOT set"
          fi
          
          if [ -n "${{ secrets.NEXTAUTH_URL }}" ]; then
            echo "✅ NEXTAUTH_URL is set"
            echo "   Value: ${{ secrets.NEXTAUTH_URL }}"
          else
            echo "❌ NEXTAUTH_URL is NOT set"
          fi
          
          if [ -n "${{ secrets.NEXTAUTH_SECRET }}" ]; then
            echo "✅ NEXTAUTH_SECRET is set"
          else
            echo "❌ NEXTAUTH_SECRET is NOT set"
          fi
          
          echo "=================================="
          echo "Note: Actual secret values are hidden for security"
        env:
          SECRET: ${{ secrets.EC2_SSH_KEY }}

      - name: Test SSH Connection
        if: ${{ secrets.EC2_SSH_KEY != '' && secrets.EC2_HOST_DEV != '' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ SSH Connection Successful!"
            echo "Hostname: $(hostname)"
            echo "Current user: $(whoami)"
            echo "Current directory: $(pwd)"
            
            # Check if Docker is installed
            if command -v docker &> /dev/null; then
              echo "✅ Docker is installed"
              docker --version
            else
              echo "❌ Docker is NOT installed"
            fi
            
            # Check if Git is installed
            if command -v git &> /dev/null; then
              echo "✅ Git is installed"
              git --version
            else
              echo "❌ Git is NOT installed"
            fi
            
            # Check if frontend directory exists
            if [ -d "/home/ec2-user/academic-saas-frontend" ]; then
              echo "✅ Frontend directory exists"
            else
              echo "ℹ️  Frontend directory does not exist (will be created on first deploy)"
            fi
            
            # Check running containers
            echo ""
            echo "Running Docker containers:"
            sudo docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"